---
title: "Profile"
---

- __Name:__ Yuri Lavinas
- __Ocupation:__ "Master Student"
- __Hobbies:__ Sports and Movies.


# Short Bio

I graduated from the University of Brasilia (UnB) (2009-2016), where I studied Genetic Algorithm, focusing on generate Earthquake Risk Models. I did some volunteer work during my undergraduate time at UnB in a junior enterpriser called CJR. There I had the opportunity to work with web development and protect management. Then, I came to Japan, where I'm currently living, as a research student at the University of Tsukuba. After a 6 month period, I entered the master course at the University of Tsukuba, Japan.

Now I am pursuing my master degree in Computer Science at the University of Tsukuba. My research interests include Evolutionary Computation and optimization as well as Neuroevolution, and their applications.

I already collaborate with the Department of Computer Science at the University of Brasilia and I'm looking foward to more!

Among non-research activities, I teach physics to brazilian highschool students.
