---
title: "Publications"

---

Send me an [e-mail](mailto:lavinas.yuri.xp@alumni.tsukuba.ac.jp) if you have any questions about these publications.

Publications are listed in chronological order, and the horizontal line separates peer-reviewed publications.

## 2024

1. *Yuri Lavinas*, Nathaniel Haut, William Punch, Wolfgang Banzhaf, 
Cussat-Blanc. **Dynamically Sampling biomedical Images For Genetic Programming**, In Proceedings of the Companion Conference on Genetic and Evolutionary Computation (GECCO '24 Companion). . https://doi.org/10.1145/3638530.3654202.  

2. *Yuri Lavinas*, Nathaniel Haut, William Punch, Wolfgang Banzhaf, 
Cussat-Blanc. **Data sampling via Active Learning in Cartesian Genetic Programming for Biomedical Data**, (CEC), Yokohama, Japan, 2024, https://doi.org/10.1109/CEC60901.2024.10611879. 

3. *Yuri Lavinas*, Nathan Haut, William Punch, Wolfgang Banzhaf, 
Cussat-Blanc. **Adaptive Sampling of Biomedical Images with Cartesian Genetic Programming**, Parallel Problem Solving From Nature (PPSN 2024), Hagenberg, Austria. https://doi.org/10.1007/978-3-031-70055-2_16

4.Camilo De La Torre, Sylvain Cussat-Blanc, Dennis G Wilson, *Yuri Lavinas*
**On Search Trajectory Networks for Graph Genetic Programming**. In Proceedings of the Companion Conference on Genetic and Evolutionary Computation (GECCO '24 Companion). . https://doi.org/10.1145/3638530.3664169

5. Camilo De La Torre, *Yuri Lavinas*, Ké=zvin Cortacero, Hervé Luga, Dennis G Wilson, Sylvain
Cussat-Blanc, **Multi-Modal Adaptive Graph Evolution for Program Synthesis**, Parallel Problem Solving From Nature (PPSN 2024), Hagenberg, Austria. (https://doi.org/10.1007/978-3-031-70055-2_16)to appear)



## 2023



1. Gabriela Ochoa, Arnaud Liefooghe, *Yuri Lavinas*, Claus Aranha. **Decision/Objective Space Trajectory Networks for Multi-objective Combinatorial Optimisation**, Evolutionary Computation in Combinatorial Optimization. EvoCOP 2023. https://doi.org/10.1007/978-3-031-30035-6_14 [Preprint.](papers/EvoStar_2023__Multi_Objective_STNs_Combinatorial_Optimisation.pdf)

2. Paul Mitchel, Gabriela Ochoa, *Yuri Lavinas*, Romain Chassagne. **Local Optima Networks for Seismic History
Matching Problems**, EvoApplications 2023. https://doi.org/10.1007/978-3-031-30229-9_6 [Preprint.](papers/FLA_of_ASHM_Problems_using_LONs___EvoStar_2023.pdf)

3.  Alexandre Mascarenhas, *Yuri Lavinas*, Claus Aranha. **AbCD: A Component-wise Adjustable Framework for Dynamic Optimization Problems**, In Proceedings of the Companion Conference on Genetic and Evolutionary Computation (GECCO '23 Companion). . https://doi.org/10.1145/3583133.3590655 [Extended version.](papers/2023_GECCO_Auto_Dynamic_PSO-1.pdf)

4. *Yuri Lavinas*, Kevin Cortacero,  Cussat-Blanc. **Evolving Graphs with Cartesian Genetic Programming with Lexicase Selection**, In Proceedings of the Companion Conference on Genetic and Evolutionary Computation (GECCO '23 Companion). Association for Computing Machinery, New York, NY, USA, 1920–1924. https://doi.org/10.1145/3583133.3596402 [Preprint.](papers/2023_GECCO_CGP_LEX-1.pdf)

5. *Yuri Lavinas*, Marcelo Ladeira, Gabriela Ochoa, Claus Aranha. **Multiobjective Evolutionary Component Effect on Algorithm behavior**, Multiobjective Evolutionary Component Effect on Algorithm behavior. ACM     Transactions on Evolutionary Learning and Optimization. Just Accepted (August 2023) https://dl.acm.org/doi/10.1145/3612933

## 2022
1. *Yuri Lavinas*, Marcelo Ladeira, Claus Aranha. **Faster Convergence in Multi-Objective Optimization Algorithms Based on Decomposition Evolutionary Computation**, 2022, Evolutionary Computation, doi: 
https://doi.org/10.1162/evco_a_00306 [Preprint.](https://arxiv.org/abs/2112.11939)

2. *Yuri Lavinas*, Claus Aranha, Gabriela Ochoa. **Search Trajectories Networks of Multiobjective Evolutionary Algorithms**, 2022 Conference on the Applications of Evolutionary Computation (Part of EvoStar), doi: https://doi.org/10.1007/978-3-031-02462-7_15 [Preprint.](https://arxiv.org/abs/2201.11726) 
- ***This work was nominated as candidate for the student best paper of EvoStar 2022.***
- ***This work was nominated as candidate for the best paper of EvoStar 2022.***

3. *Yuri Lavinas*, Marcelo Ladeira, Claus Aranha, Gabriela Ochoa. **Component-wise Analysis of Automatically Designed Multiobjective Algorithms on Constrained Problems**, 2022 GECCO, doi https://doi.org/10.1145/3512290.3528719
- ***This work was nominated as candidate for the best paper of the EMO track GECCO 2022.***
[Preprint.](https://arxiv.org/abs/2203.13447)

## 2021

1. Felipe Vaz, *Yuri Lavinas*, Claus Aranha, Marcelo Ladeira. **"Exploring Constraint Handling Techniques in Real-world Problems on MOEA/D with Limited Budget of Evaluations"**, 2021 Evolutionary Multi-Criterion Optimization (EMO), doi: https://doi.org/10.1007/978-3-030-72062-9_44 [Preprint.](https://arxiv.org/pdf/2011.09722.pdf)

- [Watch EMO 2021 presentation video on YouTube.](https://youtu.be/wOA0BnX51QI)

2. *Yuri Lavinas*, Abe Mitsu Teru, Yuta Kobayashi, and Claus Aranha. **"MOEA/D with Adaptative Number of Weight Vectors"**, In Theory and Practice of Natural Computing, pp. 134-146, Cham, 2021. Springer International Publishing, doi: https://doi.org/10.1007/978-3-030-90425-8_7. [Preprint.](https://arxiv.org/pdf/2109.05741.pdf)

-----

## 2020 

1. *Yuri Lavinas*, C. Aranha, M. Ladeira and F. Campelo, **"MOEA/D with Random Partial Update Strategy,"** 2020 IEEE Congress on Evolutionary Computation (CEC), Glasgow, United Kingdom, 2020, pp. 1-8, doi: https://doi.org/10.1109/CEC48606.2020.9185527. [Preprint.](https://arxiv.org/abs/2001.06980)

- [Watch CEC 2020 presentation video on YouTube.](https://youtu.be/0wViMZENBq4)

2. Nicolo Oreste Pinciroli Vago, *Yuri Lavinas*, Daniele Rodrigues, Felipe Moura, Sergio Cunha, Claus Aranha, and Ricardo da Silva Torres, **"INTEGRA: An Open Tool To Support Graph-Based Change Pattern Analyses In Simulated Football Matches"**, 34th International ECMS Conference on Modeling and Simulation, 2020.06 DOI: https://doi.org/10.7148/2020-0228 [Link.](http://www.scs-europe.net/dlib/2020/ecms2020acceptedpapers/0228_ocms_ecms2020_0051.pdf)

-----

1. [*Yuri Lavinas*, Claus Aranha, Marcelo Ladeira, Tetsuya Sakurai, "Resource Allocation and Population Size in MOEA/D" Symposium of the Japanese Society of Evolutionary Computation (2020.09).](papers/Resource_Allocation_and_Population_Size_in_MOEA:D.pdf)

- [Watch JSEC 2020 presentation video on YouTube.](https://youtu.be/H9rYGbS2YLY)


## 2019
1. *Yuri Lavinas*, Claus Aranha, Tetsuya Sakurai, **"Using Diversity as a Priority Function for Resource Allocation on MOEA/D"**, In Genetic and Evolutionary Computation Conference Companion (GECCO '19 Companion), https://doi.org/10.1145/3319619.3321948, 2019.7 [Preprint.](papers/Using_diversity_as_a_priority_function_for_resourc.pdf)

2. *Yuri Lavinas*, Claus Aranha, and Marcelo Ladeira. **"Improving resource allocation in MOEA/D with decision-space diversity metrics"**. In Theory and Practice of Natural Computing, pp. 134–146, Cham, 2019. Springer International Publishing, https://www.doi.org/10.1007/978-3-030-34500-6_9, 2019.12 

-----

1. [*Yuri Lavinas*, Claus Aranha, Marcelo Ladeira, Tetsuya Sakurai, **"Resource Allocation in MOEA/D: What is important?"** Symposium of the Japanese Society of Evolutionary Computation (2019.09).](papers/what_is_important_in_ResourceAllocation.pdf)


-----

## 2018

1. *Yuri Lavinas*, Claus Aranha, Tetsuya Sakurai, Marcelo Ladeira, **"Experimental Analysis of the Tournament Size on Genetic Algorithms"**, IEEE International Conference on Systems, Man and Cybernetics, pp.3647-3653, https://doi.org/10.1109/SMC.2018.00617, 2018.10. [Preprint.](https://www.researchgate.net/publication/330478320_Experimental_Analysis_of_the_Tournament_Size_on_Genetic_Algorithms)

-----

2. *Yuri Lavinas*, Claus Aranha, Tetsuya Sakurai, **"Resource Allocation by Diversity"** Symposium of the Japanese Society of Evolutionary Computation (2018.12)


## 2017

-----

1. *Yuri Lavinas*, Claus Aranha, Marcelo Ladeira, **"Experimental Analysis of the Tournament Size on Evolutionary Algorithms"** Symposium of the Japanese Society of Evolutionary Computation (2017.12) 

## 2016

-----

1. *Yuri Lavinas*, Marcelo Ladeira, Claus Aranha, **"Inducao de Modelo de Risco de Sismos com Tecnicas de Algoritmos Geneticos"** - 68th Annual Meeting of the Brazilian Science Society (SBC) (2016.7) (Poster, in Portuguese).

## 2014

-----

1. Claus Aranha, *Yuri Cossich Lavinas*, Marcelo Ladeira and Bogdan Enescu: **"Is it possible to generate good Earthquake Risk Models using Genetic Algorithms?"**, 6th International Conference on Evolutionary Computation Theory and Applications (ECTA), Rome,  2014, https://doi.org/10.5220/0005072600490058.
